# Generated by Django 3.2.8 on 2021-10-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.TextField(default='', max_length=5000),
        ),
    ]
